### ISSUE TITLE
Rename _build to something else

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#10]
`_build` is the same name that ocamlbuild uses for running builds. Since a lot of the potential users of jbuilder might be migrating from ocamlbuild, avoiding this possible conflict might be helpful.

Also, it's not unthinkable that some people might want to use jbuilder and ocamlbuild in the same project. Might as well make it as easy as possible for them.

**Comment by diml** [comment]
This makes sense, although I quite like `_build`...

Possible alternatives:
- `.build`
- `_jbuild`
- `_artifacts`

**Comment by rgrinberg** [comment]
`_jbuild` is good. Will create a revision.

**Comment by samoht** [comment]
Why is this an issue to share the `_build` directory?

**Comment by diml** [comment]
I guess it might be a bit confusing if you forget to do a clean between runs of ocamlbuild and jbuilder. Otherwise I don't think there is a technical issue, except if there is a conflict between the files produced by jbuilder and ocamlbuild, for instance if you have a directory `default` at the root of your project.

@rgrinberg, can you think of something else?

**Comment by samoht** [comment]
I think it would be better to keep `_build` if possible. Mixed build systems in the same project is a very rare thing.

**Comment by diml** [comment]
I prefer that as well. I need to do another alpha release of jbuilder so that I can do another alpha release of Base, so I'm reverting the changes for now.

We can revisit this decision later if we experience problems with using `_build` or if there is a better consensus. At worse, ocamlbuild has a `-build-dir` option, and we could add one to jbuilder as well with a bit of refactoring.
