### ISSUE TITLE
OCaml and preprocessor have incompatible versions

### ISSUE THREAD

**Issue by mads-hartmann** [janestreet/jbuilder#157]
I was trying to get `jbuilder` to compile a simple hello-world application written in Reason. However, I got the following error:

```
ocamldep main.depends.ocamldep-output (exit 2)
(cd _build/default && /usr/local/bin/ocamldep.opt -modules main.re.ml) > _build/default/main.depends.ocamldep-output
>> Fatal error: OCaml and preprocessor have incompatible versions
Fatal error: exception Misc.Fatal_error
```

You can see my example here: https://github.com/mads-hartmann/random/commit/047ecdd8fca67fbd526a523e40cc85fb11fe0cab

Let me know if I can help with anything.

**Comment by rgrinberg** [comment]
That doesn't seem like an issue with jbuilder.. What version of ocaml/reason/ocaml-migrate-parsetree are you using?

cc @jordwalke

**Comment by jordwalke** [comment]
Usually this error message occurs when something is using ocamlrun on an artifact that was compiled for a different version of the AST I believe.  Can you also show me the result of `opam list`?

cc @jaredly while I investigate. Jared has built a scaffolding tool for using Reason and JBuilder to create CLI applications.

https://twitter.com/jaredforsyth/status/876182275813244930

**Comment by mads-hartmann** [comment]
Thanks for responding so quickly. I think you're right in assuming this isn't strictly a jbuilder issue but rather a faulty setup on my machine.

- opam version: `1.2.2`
- ocaml version: `4.02.3`

opam packages

```
# Installed packages for system:
base-bigarray       base  Bigarray library distributed with the OCaml compiler
base-threads        base  Threads library distributed with the OCaml compiler
base-unix           base  Unix library distributed with the OCaml compiler
conf-m4                1  Virtual package relying on m4
jbuilder       1.0+beta9  Fast, portable and opinionated build system
ocamlfind          1.7.2  A library manager for OCaml
```

I have `reason-cli@1.7.3` installed as a global npm package (which crashes when I try to uninstall it for some reason)

I will try out https://github.com/jaredly/ohai later today 😊

**Comment by mads-hartmann** [comment]
Alright, I managed to uninstall `reason-cli` and do a normal install of reason using opam. This fixed it for me. Sorry for the inconvenience, I appreciate the help 👍

**Comment by jordwalke** [comment]
@mads-hartmann Just for my own curiosity, was your version of reason-cli really old? When did you install it?

**Comment by mads-hartmann** [comment]
@jordwalke It was `git://github.com/reasonml/reason-cli.git#beta-v-1.13.5`. I had to upgrade to 1.13.6 before I could uninstall it, but to be fair it seems that perhaps my `npm` (v5.0.3) installations is broken (at least there are other pacakges that crashes it when I try to uninstall them) 😊

**Comment by jordwalke** [comment]
Yeah, I've heard about some problems with npm5. You can also try the binary releases as well which people are reporting to be pretty stable: https://github.com/reasonml/reason-cli#1-install-a-specific-release

**Comment by mads-hartmann** [comment]
@jordwalke I'm fairly comfortable using opam so I'll just stick with having everything installed that way 😊

**Comment by jordwalke** [comment]
Great, it is still the recommended approach especially for anyone who is familiar with how to use opam. Please drop a line in the #lookwhatibuilt channel in Discord to share what you end up building!

**Comment by jbranchaud** [comment]
I recently started working with Dune and I am seeing this error when trying to build a small Cohttp example ([Cohttp client tutorial](https://github.com/mirage/ocaml-cohttp)) that I've ported to Reason.

OCaml Version: 4.07.0
Reason Version: 3.3.3

I'm not sure how much of the original advice in this thread has changed. I originally installed Reason/reason-cli through `bs-platform`.

Any thoughts or advice would be much appreciated!

**Comment by brando90** [comment]
what is the preprocessor? what does the rror:

    >> Fatal error: OCaml and preprocessor have incompatible versions

mean?

**Comment by diml** [comment]
A preprocessor is a program that transform the source code before it is given to the compiler. Preprocessors are commonly used to do simple and textual transformations such as expanding macros.

In general, a preprocessor takes source code as input and outputs the transformed source code. However, in OCaml a preprocessor is allowed to output a pre-parsed binary representation of the source code, called the AST (Abstract Syntax Tree). This has several advantages:
- it avoids doing the parsing twice, so it is faster
- it is easier to preserve locations when doing complex transformations, so that error messages point to the right place

However, for this feature to work, both the preprocessor and compiler must agree on the binary representation of the source code. This representation is tied to the version of the OCaml compiler. Technically, that means that if you build a preprocessor with OCaml 4.06.0, then you cannot use this preprocessor to build an OCaml source file with OCaml 4.07.0. If you try to do so, then you get the error you mentioned.
