### ISSUE TITLE
content of jbuild-workspace ignored if the file has an extension

### ISSUE THREAD

**Issue by c-cube** [janestreet/jbuilder#234]
I have a file `jbuild-workspace.dev` at the root of my project, containing several `(context ((switch foo)))`, but they are ignored during build. If I rename the file into `jbuild-workspace` it works.

**Comment by dra27** [comment]
This is the correct behaviour - see the [manual](http://jbuilder.readthedocs.io/en/latest/usage.html?highlight=jbuild-workspace#id2) for the explanation.

**Comment by dra27** [comment]
The idea behind it is that you should commit jbuild-workspace.dev as an empty file to every repository (in order to stop jbuilder ever escaping your worktree) but you should not normally be committing jbuild-workspace to source control, because it refers to your local set-up.

**Comment by c-cube** [comment]
Ah, I see. The docs on workspace are a bit sparse :-)

**Comment by lpw25** [comment]
I lost quite a lot of time the other day to the inverse problem: if you have an empty `jbuild-workspace` file rather than a `jbuild-workspace.dev` file then things don't work properly -- you don't get a proper error message it just tries to do what you're asking for and then fails in some incomprehensible way.

I don't really see the need to differentiate `jbuild-workspace` and `jbuild-workspace.dev` files by filename. Why not just treat both the same, with an empty one equivalent to `(context default)`? Then people can still put an empty one in their project, and keep local ones outside of there projects, but there won't be any confusion between the two kinds of file.

**Comment by dra27** [comment]
I certainly agree that treating an empty `jbuild-workspace` as though it contained `(context default)` is a good idea.

I'm not so sure about treating them in the same way, if the main aim is to ensure that build context information is never committed to source control. I guess what might have been cleaner (or could still be done) is to look for `jbuild-root` (an empty file) if `jbuild-workspace` isn't found, and eliminate the similarity in filenames entirely?

**Comment by diml** [comment]
The initial idea was that I was often adding `jbuild-workspace.dev` files in my projects to test all the versions of OCaml I wanted to support. So the current rules for finding the root avoided adding yet another file at the root of the project.

> I certainly agree that treating an empty jbuild-workspace as though it contained (context default) is a good idea.

Seems fine to me as well.
