### ISSUE TITLE
building library with examples

### ISSUE THREAD

**Issue by vzaliva** [janestreet/jbuilder#271]
I have a simple library (say `mylib.ml`) and also want to compile an example of it's usage (say `myex.ml`).
Trying something like:

```
(jbuild_version 1)

(library 
  ((name mylib)
))

(executable
             ((name example)
             (libraries (batteries))
             ))

```
gives an error: `Multiple rules generated for _build/default/mylib.o`. 

How can I build something like this?

**Comment by hcarty** [comment]
I'm not 100% certain about the jbuilder rules here, but you may need to put the example in its own directory with its own `jbuild` file.

**Comment by vzaliva** [comment]
The top level package is the library I am trying to build. If I put examples in sub-package under it they would need to depend on the library (parent package). I am not sure that would work....

**Comment by dra27** [comment]
This is not a bug or issue with Jbuilder - questions like this would be better posted on the [OCaml Discuss forum](https://discuss.ocaml.org/), so please continue the discussion there if necessary. It's not a problem to answer them here, but there are more Jbuilder users on Discuss than there are developers monitoring the issue tracker.

The problem here is that your jbuild files lacks `modules` fields so both the library and the executable include `mylib.ml`. The error message could be clearer, but this is already a known problem. @hcarty is correct that putting the library and example in separate directories would solve the problem (and I'll come on to your comment about referring to the parent package shortly).

You cannot have an executable example defined in `myex.ml`, so correcting two bits of the jbuild file so far:

<pre>
(jbuild_version 1)

(library 
  ((name mylib)
   <strong>(modules (mylib))</strong>
))

(executable
             ((name <strike>example</strike><strong>myex</strong>)
             (libraries (batteries))
             <strong>(modules (myex))</strong>
             ))
</pre>

You can now run `jbuilder build myex.exe` and you will get an error about Mylib not being found. Regardless of whether you put the example in a separate directory with its own jbuild file or keep it in the current directory, you must refer to it in the `libraries` field of the `executable` stanza - i.e. you need `mylib` with `batteries`.

Note also that you're defining a library `mylib` and having a single module `mylib.ml` is probably not the effect you want. Here, for a toy example, you probably want to add `(wrapped false)` to your `library` stanza or if you add another module to your library you're going to get a surprise when that module is inaccessible from the example. Without `(wrapped false)` Jbuilder emulates namespaces for libraries. Suppose you have two files `bar.ml` and `baz.ml`, then this:

```
(library
  ((name foo)
   (modules (bar baz))))
```

creates a library where the modules are referred to as `Foo.Bar` and `Foo.Baz`. If you also provide `foo.ml` and include that in the `modules` field (which is effectively what you've done above) then this allows you to control which modules are exported, for example, `foo.ml` could contain:

```ocaml
module Bar = Foo__Bar
```

at which point the module Baz becomes internal to your library.
