### ISSUE TITLE
Run tests command

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#3]
I understand this isn't implemented yet, but it's a pre-requisite for me to actually use jbuilder in a couple of open source projects. What's the ETA on having this?

If this isn't a priority, then perhaps I can help on this?

**Comment by diml** [comment]
I haven't started the work, but some help would be nice indeed. Basically the way we handle running tests in jenga is through aliases, which are similar to Makefile `.PHONY` targets. Aliases are targets starting with a dot, so to run tests one has to type:

```sh
$ jenga .runtest
```

This will run tests in the current directory and recursively in all children. Tests can then be defined by writing in the jbuild:

```scheme
(alias
  ((name runtest)
   (action "./my-test-runner blah")))
```

which means that to build the `runtest` alias in the current directory one has to run `./my-test-runner blah`.

Aliases are mostly setup inside, but not yet exposed. There are two things left to do:

1. implement `(alias ...)` stanzas
2. allow the users to request an alias to be built (currently `jbuilder .runtest` will just fail)

### `(alias ...)` stanzas

For (1), you need to add a module like this in `src/jbuild_types.ml`:

```ocaml
module Alias_conf = struct
  type t =
    { name  : string
    ; deps  : Dep_conf.t list
    ; action : User_action.Unexpanded.t option
    }

  let t =
    record ...
end
```

`deps` is a list of additional dependencies of the alias. Then you need to implement the rules corresponding to this stanza in `src/gen_rules.ml`. You can look at the `user_rules` function, this will be quite similar.

In order to add dependencies to an alias internally, you need to call `Alias.add_deps`, for instance:

```ocaml
Alias.add_deps (Alias.make "runtest" ~dir) [path1; path2; ...]
```

You can only add path dependencies to an alias in jbuilder, so to force the command to be run, you can touch a dummy file and add this file as a dependency of the alias. For the dummy file, you can use the alias name + a digest of the action. To take the digest, you can convert the action to a s-expression, then to a string and digest that. You'll need to add a `User_action.sexp_of_t` function.

To touch a dummy file you can write:

```ocaml
Build.return "" >>> Build.echo path
```

You can add this as a `Build.touch` function

### request an alias to be built

Currently aliases are just implemented as files in jbuilder, i.e. building alias `foo` is the same as building a special file, which is currently `.jbuild-alias-foo` (this is defined in `Alias.make`). I haven't thought how to expose aliases to users, but I guess we could simply change the special file to be `.foo`, that shouldn't be an issue and will make things simple.

However there is still a minor issue: because we use a separate build directory, you would have to write:

```sh
$ jbuilder _build/default/.runtest
```

to run the tests, which is not ideal. I can think of two ways to improve this:

- when the user request a target that is not inside `_build`, we automatically prepend `_build/default`. Although we'll need a special case for `.install` file since we really want them outside of `_build` so that opam can find them
- as you suggested, we add a `jbuilder runtest [<dir>]` command, which will do the right thing

I'm leaning toward the second option

### Inline tests

We also have special support for inline tests in our jenga rules, i.e. when you write `let%test` in an ml file, running this test will be setup automatically. But unless you are interested in inline tests, I can write the code to set them up myself
