### ISSUE TITLE
Feature request: `public_name` for executables

### ISSUE THREAD

**Issue by stedolan** [janestreet/jbuilder#33]
I'm really liking jbuilder - it's reduced the number of moving parts in a build quite significantly. One of the few things that still irks me is that there's a bit too much boilerplate to define an executable.

I'd like to be able to write (by analogy with the `library` stanza):
```
(executables
 ((name foo)
  (public_name bar)))
```
and have it work the same as what I currently write:
```
(executables
 ((names (foo))))
(install
 ((section bin)
  (files ((foo.exe as bar)))))
```

(It's also unclear to me why jbuilder uses single for `library` but plural for `executables`, and why a library has one `name` but an executable has several `names`. Is this a historical accident or a use-case I haven't run into yet?)

**Comment by diml** [comment]
The idea is that in general you have directories containing only one library, and then you have directories containing a set of executables, all sharing the same build configuration.

Defining multiple libraries in a single directory is supported but there are pitfalls:
- you can only have one .merlin file per directory so it has to be merged into a superset of all the configurations
- you need to specify the lists of modules explicitly since the build system cannot guess which module is part of which library

One the other hand, defining several executables at once works just fine and is more convenient than having multiple `(executable ...)` stanzas, especially if they are long and all the same.

Adding an `(executable ...)` stanza seems fine to me. I always get bitten by this; I start by writing `(name blah)` and then get a syntax error so happy to add it. `(public_name ...)` seems good as well.

So we can add the two following syntaxes:

```scheme
(executable
  ((name        foo)
   (public_name bar)
   ...))

(executables
  ((names        (foo_main bar_main))
   (public_names (foo      -       ))
   ...))
```

where `-` means don't install.

**Comment by diml** [comment]
I added this, it's indeed nicer. I also had to add a `(package <pkg>)` field so that one can specify the package when there are several in the same repository.

**Comment by stedolan** [comment]
That was quick. Thanks!
