### ISSUE TITLE
--version flag

### ISSUE THREAD

**Issue by jnfoster** [janestreet/jbuilder#417]
Executing 
```
jbuilder --version
```
returns
```
%%VERSION%%
```

**Comment by dra27** [comment]
I assume this is building from sources? You need to run `./boot.exe --subst` before `./boot.exe` to update the version number watermark (see `jbuilder.opam` in the root).

**Comment by jnfoster** [comment]
Ahh. This was from cloning the GitHub repository and then running 
> make release
> make install

as instructed in the `README.md` file. 

Perhaps those instructions or the Makefile should be updated to run `boot.exe` with the `--subst` command-line option?

**Comment by dra27** [comment]
The `Makefile` should not, I think - it updates the source tree, and I think we'd start seeing pull requests where the watermark change was committed.

The readme recommends installing via opam as the main mechanism - `opam pin add jbuilder --dev-repo` does the subst. If you're cloning to develop it, I'm not convinced that having the version reported 'accurately' is important.

**Comment by dra27** [comment]
The `Makefile` should not, I think - it updates the source tree, and I think we'd start seeing pull requests where the watermark change was committed.

The readme recommends installing via opam as the main mechanism - `opam pin add jbuilder --dev-repo` does the subst. If you're cloning to develop it, I'm not convinced that having the version reported 'accurately' is important.

**Comment by diml** [comment]
One thing we could do is change jbuilder so that when the version of a package evaluates to `%%VERSION%%`, it uses the output of `git describe ...` instead. So we could write in the jbuild file:

```scheme
(rule (with-stdout-to version.ml (echo "let version = {|${version:jbuilder}|}")))
```

I've seen this in some projects such as https://github.com/ocaml-ppx/ocamlformat.

To make things even more simpler, jbuilder could provide a special `build_info` library with this API:

```ocaml
val version : string
val linked_in_libraries : string list
...
```

whose implementation would be automatically generated at link time.
