### ISSUE TITLE
Suggetion: Move vendored libs to own dir

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#6]
Having a structure such as:

```
vendor/re
vendor/cmdliner
```

Would make this repo a little easier to work with. For example, it will grep a lot more useful.

I realize that this might complicate the bootstrapping but perhaps it's worth it.

**Comment by diml** [comment]
That seems reasonable to me. It should be straightforward to adapt the bootstrap; we compile everything at once so we just need to update the paths. BTW note that there is already an overlay for ocaml-re in the bootstrap. Since it's not used to build jbuilder itself, it's replaced by a dummy implementation to speed things up. I suppose we could do something similar for Cmdliner, i.e. just remove Main and Cmdliner from the list of modules to include and replace them by a small piece of code that request the build of `jbuilder.install`

**Comment by diml** [comment]
done
