### ISSUE TITLE
support for watermarking source files

### ISSUE THREAD

**Issue by samoht** [janestreet/jbuilder#67]
Topkg has the great feature to be able to watermark source files depending on the context: see http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALwatermarks

`VERSION` has a special treatment: for releases, it is exactly the package version. When compiled in `--dev` mode (or the equivalent) it uses `git describe`. So if you get a binary built in dev mode, it's easy to set the output of `<binary> --version` to the right thing, just use [let version = "%%VERSION%%"](https://github.com/mirage/irmin/blob/master/src/ir_version.ml#L1) in your program.

**Comment by diml** [comment]
The variables are only expanded when creating the distribution archive, right?

It seems to me that it'd be better if these where done on the fly. For storing the version in the executable, the way that would fit the best in jbuilder is to add a `${version:<package>}` variable, so that you can write:

```scheme
(rule
 ((targets (version.ml))
  (action (with-stdout-to ${@} (echo "let version = \"${version:foo}\"")))))
```

Or use a preprocessor and pass it the version.

For documentation, it seems to me that it'd be better to be able to do something like `odoc -D version=42` and then use `version` as a variable in the documentation.

**Comment by diml** [comment]
The `git describe` seems good though. We could use this as default when no explicit version is defined by the user

**Comment by samoht** [comment]
On-the-fly replacement works too, as long as it works transparently between dev mode / release mode.

Regarding the substitution rule, it would probably be better to have something a bit more evolved, e.g.

```
((rule
  ((targets (version.ml)
   (deps     (version.ml.in)
   (action   (subst ${<} ((VERSION ${version:foo})
                                       (AUTHOR "Me Me!"))))
```

And it would be great to have a way to extract info for the opam file fields, e.g. `%{opam:dev-repo}` to get the contents of the `dev-repo` field in the opam file.

**Comment by diml** [comment]
This `subst` idea could be useful as a portable replacement for sed. Since we embed ocaml-re we could do interesting things without too much hassle. This should help writing simple rules.

For `${opam:...}`, why not. To do that properly we might end up having to add a proper parser for opam file. I was thinking about this, so that jbuilder can print warnings when you have multiple packages in your project and dependencies are wrong.

TBH, both of these feature are not hight priority on my list. Happy to help if someone wants to work on these features though.

There is still something I don't fully grasp for the version thing. If we implement the changes described in this thread, when you pin a development package the version in the META file and in the documentation/code will be the fancy one and the version opam sees will be something else, which will be confusing for users.

AFAIU, when you pin a package, opam will use the version in the opam file if it finds one. How does that work with topkg? Does ocamlfind and opam reports different versions?

**Comment by samoht** [comment]
Topkg uses the `pinned` variable defined by opam: https://github.com/dbuenzli/tsdl/blob/master/opam#L28

So it knows in which mode it is running, and can choose the appropriate way to compute the version.

**Comment by diml** [comment]
I don't understand how this help setting the opam version. I tried with react as I couldn't install tsdl:

```
$ opam pin add --dev react
[...]
$ opam info react -f version
1.2.1
$ ocamlfind list|grep react
react               (version: 1.2.0-18-gd9c6338)
react.top           (version: 1.2.0-18-gd9c6338)
$ grep Release .opam/4.04.0/doc/react/README.md 
Release v1.2.0-18-gd9c6338
```

I think this is confusing

**Comment by samoht** [comment]
But you also have:

```
$ opam info react -f pinned
git (d9c6338c)
```

e.g. opam has the information, it is just not shown in the `version` field (maybe it should)

**Comment by diml** [comment]
I think jbuilder and opam should agree on the version, otherwise it's messy.  Currently the recommended way to set the version is to put it in the opam file. You don't get fancy versions but at least things are consistent.

Something need to be changed in opam to use `git describe --tags` as version when appropriate. I prefer to wait for this to happen before changing jbuilder.

You can however use the following jbuild file as a temporary workaround (js_of_ocaml does something like this):

```ocaml
(* -*- tuareg -*- *)
#require "unix"
let git_version =
  if not (try Sys.is_directory ".git" with _ -> false)
  then ""
  else
    let ic = Unix.open_process_in "git describe --tags" in
    let version = input_line ic in
    close_in ic;
    version

let () = Printf.ksprintf Jbuild_plugin.V1.send {|
(jbuild_version 1)

(rule
 ((targets (foo.version))
  (action (with-stdout-to ${@}
           (echo %S)))))
|} git_version
```

**Comment by diml** [comment]
I implemented the support for `${version:<package>}`

**Comment by samoht** [comment]
Thanks!

About "jbuilder and opam should agree on the version": although that seems like a good idea, opam explicitly allow to overwrite the version when pinning, e.g. you can do:

```
opam pin add foo.<v1> https://github.com/foo/foo.git#v2
```

e.g. you can install an old/new version and in the context of an new/old version. It's very useful when you try to fix version constraint issues.

**Comment by diml** [comment]
Thinking more about this, setting the version on the fly might not be too great for incremental compilation.

I looked more in details at topkg and the watermarking doesn't seem too bad in the end. In the topkg branch I started writing some helpers to use topkg with jbuilder, at least topkg-care. I have something working for releases. I also added a subst command that does the same substitution as topkg, so that you can write in opam files:

```
build: [
  ["jbuilder" "subst"] {pinned}
  ["jbuilder" "build" "-p" name "-j" jobs]
]
```

**Comment by diml** [comment]
I merged the topkg stuff, you can now use watermarks in projects using jbuilder
