### ISSUE TITLE
Configuration using opam conf-XXX packages

### ISSUE THREAD

**Issue by andrewray** [janestreet/jbuilder#95]
In Lwt conf-libev is used to enable optional support.  This is passed via opam to a feature discovery script.  It seems to also be used for development as a feature switch.  There is no corresponding findlib package.

I am not sure of the best approach to support what are essentially `--enable-FEATURE` arguments to the build process, discovered by opam.

**Comment by diml** [comment]
I would do the following:

1. write a simple ocaml script that takes these `--enable-FEATURE` options and dump them to a config file
2. call the script from the `build:` field before calling jbuilder
3. change the discover script to read this config file and act accordingly

Then you could also write a rule to produce a default config file, so that calling the script is optional. When jbuilder has a rule to produce a file but this file already exists in the source tree, it will ignore the rule.

**Comment by andrewray** [comment]
Gotcha.  Thanks.
